name: Rust

on:
  push:
    branches: [ "master" ]
    paths:
      - "src/**"
      - "test/**"
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose --release
    - name: Store builds
      uses: actions/upload-artifact@v4
      with:
        name: build-${{matrix.os}}
        # truly amazing
        path: target/release/rs-gimp-to-icc${{matrix.os == 'windows-latest' && '.exe' || ''}}


    
