name: Rust

on:
  push:
    branches: [ "master", "actions_test" ]
  pull_request:
    branches: [ "master", "actions_test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    # build for Linux and Windows
    - name: Build Windows
      run: cargo build --verbose --release --target x86_64-pc-windows-msvc
    - name: Build Linux
      run: cargo build --verbose --release --target x86_64-unknown-linux-gnu
    - name: Store builds
      uses: actions/upload-artifact@v4
      with:
        name: dist-without-markdown
        path: |
          target/release/rs-gimp-to-icc
          target/release/rs-gimp-to-icc.exe

    
